sprint 9
S-Gilliver/java-filmorate pull request #4
Opened 2023-08-10 22:56 UTC by S-Gilliver

2023-08-11 00:38 UTC, S-Gilliver commented
sprint 9

2023-08-11 18:50 UTC, kalitva requested changes

2023-08-11 18:50 UTC, kalitva commented on pom.xml
> +	<parent>
Форматируй файл по четыре пробела вместо табов

2023-08-11 18:50 UTC, kalitva commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
Удали коммент

2023-08-11 18:50 UTC, kalitva commented on pom.xml
> +			<version>1.18.20</version>
Версию лучше не определять, если уже определена в родительском поме

2023-08-11 18:50 UTC, kalitva commented on pom.xml
> +			<artifactId>junit-jupiter-api</artifactId>
Junit уже есть в spring-boot-starter-test

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final Map<Integer, Film> filmsMap = new HashMap<>();
`filmsMap --> films`
Не используй в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @GetMapping()
Скобочки не нужны если не передаешь параметр в аннотацию

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("Фильм успешно добавлен!");
Логи только по английски, иначе можешь получить что-то типа ?????? ??? ??????

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film updateFilm(@RequestBody @Valid Film film) throws NotFoundException {
Не надо декларировать `throws`

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void filmValidator(Film film) throws ValidationException {
`filmValidator --> validateFilm`

Имена методов только глаголы или глагольные словосочетания

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +import java.util.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

2023-08-11 18:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +}
Те же замечания, что и для `FilmController`

2023-08-11 18:50 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Давай удалим этот файл

2023-08-11 20:05 UTC, S-Gilliver commented
style: исправление импортов, pom.xml и т.д.

2023-08-11 20:57 UTC, kalitva requested changes

2023-08-11 20:57 UTC, kalitva commented on pom.xml
> +		<groupId>org.springframework.boot</groupId>
Не вижу чтобы файл был форматирован, пожалуйста, разберись с этим

2023-08-11 20:57 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void validateFilm(Film film) throws ValidationException {
Пожалуйста, не декларируй `throws` для рантайм исключений

2023-08-11 20:57 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if ((user.getName() == null) || user.getName().isEmpty()) {
Это на самом деле не является валидацией, лучше вынести из данного метода

2023-08-11 20:57 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import javax.validation.constraints.*;
Пожайлуйста, не используй wildcard импорты, внимательно проверь везде

2023-08-11 20:57 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Positive
Нет необходимости валидировать айдишник

2023-08-12 13:51 UTC, S-Gilliver commented
Исправлены все замечания в том числе pom.xml

2023-08-12 14:07 UTC, S-Gilliver commented
Исправлены все замечания в том числе pom.xml

2023-08-12 18:48 UTC, kalitva approved these changes

2023-08-12 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +}
Здесь тоже - замени табы на отступы по 4 пробела

2023-08-12 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Давай вместо `@Data` использовать 

```java
@Getter
@Setter
```

Иногда из-за этого могут быть проблемы

2023-08-12 19:26 UTC, merged