sprint 10
S-Gilliver/java-filmorate pull request #5
Opened 2023-08-17 20:54 UTC by S-Gilliver

2023-08-19 18:39 UTC, kalitva requested changes

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/comparator/UserComparator.java
> +public class UserComparator implements Comparator<Film> {
Давай лучше использовать не класс, а лямбду

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public void handleBadRequest(HttpServletResponse response) throws IOException {
1. Не надо декларровать `throws`
2. Давай залогируем исключения, для этого принимай их как параметр https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-exceptionhandler.html

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @ResponseStatus(HttpStatus.OK)
Статус 200 и так возвращается если не случилось исключения, нет необходимости указывать явно

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public String addLike(@PathVariable(value = "id") Integer id,
`public String addLike(@PathVariable Integer id,`
Можно не передавать имя переменной, если оно совпадает с именем параметра метода

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
Лучше `friends --> friendIds`

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return list.subList(0, count);
Давай сделаем все это с помощью стрим апи

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (Exception e) {
Вот это не очень, не очевидно откуда конкретно исключение вылетит и почему, необходимо обойтись без этого try-catch

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/ServiceValidator.java
> +public class ServiceValidator {
Обычно, если требуется достаточно много валидации, для каждой сущности заводят валидатор, т.е. нужен был бы `FilmValidator`, `UserValidator`. Но в данном случае я предлагаю вообще убрать этот класс и методы переместить в соответствующие сервисы

2023-08-19 18:39 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/ServiceValidator.java
> +            film.setLikes(new HashSet<>());
При валидации не следует  делать выполнять рода побочные действия. Инициализируй хэшсеты прямо в моделях

2023-08-19 22:37 UTC, S-Gilliver commented
Исправлены все замечания

2023-08-20 15:11 UTC, kalitva requested changes

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        return new ErrorResponse(
Не вижу чтобы исключения были залогированы

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
`likes --> likeIds`

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public String addLike(Integer id, Integer userId) {
Сделай метод `void`

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public String deleteLike(Integer id, Integer userId) {
Тоже void

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public String addFriend(Integer id, Integer friendId) {
void, этот и метод ниже

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> getFriendList(Integer id) {
`getFriendList --> getFriends`
Не используй в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getLikes() == null) {
Пожалуйста, инициализируй поле лайков пустым хэшсетом

2023-08-20 15:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if ((user.getName() == null) || user.getName().isEmpty()) {
Это должно быть в сервисе

2023-08-20 16:44 UTC, S-Gilliver commented
Исправлены все замечания

2023-08-20 18:04 UTC, S-Gilliver commented
Исправлены все замечания

2023-08-21 14:28 UTC, kalitva approved these changes

2023-08-21 14:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                + userStorage.getUserById(userId).getLogin()
Далее у нас стораджи будут работать с БД и обращаться к БД только для того чтобы что-то залогировать вряд ли хорошая идея (если, конечно, нет такого требования в тз). Залогируй айдишник пользователя, этого будет более чем  достаточно

То же для всех аналогичных случаев

2023-08-21 14:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user.setFriendIds(new HashSet<>());
Еще раз - инициализируй поле `fiendIds` пустым хэшсетом в прямо в модели

2023-08-21 14:46 UTC, merged