sprint 11
S-Gilliver/java-filmorate pull request #7
Opened 2023-08-22 15:57 UTC by S-Gilliver

2023-08-22 18:47 UTC, S-Gilliver commented
11 sprint

2023-08-23 16:36 UTC, kalitva requested changes

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final GenreStorage genreDbStorage;
`genreDbStorage --> genreStorage`

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            f.setGenres(genreDbStorage.getByFilmId(f.getId()));
Совершенно верно - доставать списки отдельным запросом, причем делать это в сервисе

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            f.setMpa(mpaDbStorage.getByFilmId(f.getId()));
А вот mpa желательно присоединить к фильму на стороне БД с помощью `join`

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getFilmById(id).orElseThrow(() -> new NotFoundException("The movie with id " +
Давай для проверки что запись существует в БД создаим отдельные методы

 ```java
if (!filmStorage.containsFilm(id) {
    throw...
}
```

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            for (Genre g : film.getGenres()) {
Можем также возпользоваться `batchUpdate`?
Плюс, удаление и добавление жанров я бы перенес в методы в `GenreStorage`, вызывая их из сервисов

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                "limit ?";
Пожалуйста, придерживайся единого стиля, если уже начал писать запросы в смешанном кейсе, делай так везде. Ну или перепиши все запросы в lower case

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +        SqlRowSet genreRows = jdbcTemplate.queryForRowSet(sql, id);
Не понял зачем rowset?

2023-08-23 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaDbStorage.java
> +        if (mpas.size() != 1) {
? Используй `JdbcTemplate#queryForObject`

2023-08-23 18:32 UTC, S-Gilliver commented
Исправлены все замечания

2023-08-23 18:51 UTC, kalitva approved these changes

2023-08-23 18:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        containsFilm(id);
Не так писал, посмотри внимательнее замечание по `contains`

2023-08-23 18:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +        List<Genre> genreList = jdbcTemplate.query(sql, genreMapper, id);
`genreList --> genres`

2023-08-23 18:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +        for (Genre g : genres) {
Используй `batchUpdate`

2023-08-23 18:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaDbStorage.java
> +        SqlRowSet mpaRows = jdbcTemplate.queryForRowSet(sql, id);
Пожалуйста, давай обойдемся без `SqlRowSet`

2023-08-23 18:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaDbStorage.java
> +    public Mpa getByFilmId(int id) {
Либо везде возвращай сущность обернутую в `Optional`, либо везде необернутую

2023-08-23 18:51 UTC, kalitva commented on src/main/resources/schema.sql
> +);
`UNIQUE` же тоже нужен?

2023-08-23 18:51 UTC, kalitva commented on src/main/resources/schema.sql
> +SELECT
Удали это

2023-08-23 20:15 UTC, S-Gilliver commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +        for (Genre g : genres) {
Я пытался использовать batchUpdate, но у меня никак не получается, можно ли так оставить?

2023-08-23 21:19 UTC, merged